package lsp

const (
	ERRCODE_SERVER_NOT_INITIALIZED int = -32002
	ERRCODE_UNKNOWN_ERROR_CODE     int = -32001
	ERRCODE_REQUEST_FAILED         int = -32803
	ERRCODE_SERVER_CANCELLED       int = -32802
)
